### ISSUE TITLE
[Feat] Realm CRUD 매니저 선언

### ISSUE THREAD

**Issue by heydoy** [here-y-seo/Team6#11]
## 🛠 Issue
Realm 저장할 데이터모델을 CRUD하는 매니저를 선언합니다. 
Repository 패턴으로 선언합니다.

## 📝 To-do

- [x] 데이터 생성 함수 !
- [x] 데이터 읽기 함수 !
- [x] 데이터 수정 함수 
- [x] 데이터 삭제 함수
