### ISSUE TITLE
[Add] 배포 설정 변경하기

### ISSUE THREAD

**Issue by heydoy** [here-y-seo/Team6#41]
## 🛠 Issue
배포 설정 변경하기

## 📝 To-do
- [x] Appearance = 라이트모드
- [x] 타겟 OS = 15.0
- [x] 타겟 디바이스 = 아이폰만
- [x] 오리엔테이션 = 아이폰,아이패드 둘 다 portrait
- [x] 개발언어 = 한국어
- [x] 앱 이름 '좋을지도'
- [ ] 번들 identifier : GoodDeedMap / 프로비저닝 프로필 추가

**Comment by heydoy** [comment]
번들 아이덴티파이어를 바꾸려면 프로비저닝 프로필도 바꾸어야한다...!
